version: '3'

services:
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - todo_vol:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "${DJANGO_SUPERUSER_USERNAME}"]

  backend:
    image: aeonix1992/my_todo_list_backend:0
    restart: always
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy

  frontend:
    image: aeonix1992/my_todo_list_frontend:0 
    restart: always
    ports:
      - 127.0.0.1:80:80
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
      backend:
        condition: service_started

  backend-migrations:
    image: aeonix1992/my_todo_list_backend:0 
    env_file:
      - .env
    command: bash -c "make migrate"
    depends_on:
      database:
        condition: service_healthy
      backend:
        condition: service_started

  backend-superuser:
    image: aeonix1992/my_todo_list_backend:0
    env_file:
      - .env
    command: bash -c "make create-superuser"
    depends_on:
      database:
        condition: service_healthy
      backend:
        condition: service_started
      backend-migrations:
        condition: service_started

volumes:
  todo_vol:
